function new_position = walk(people_position, velocity, map_size,field_of_map,grid_people_map)
    
    x = people_position(:,1);
    
    velocity = velocity ./ max(velocity')';
    velocity(velocity ~= 1) = 0;
    
    sence_v = zeros(numel(x),2);%numel(x)代表人数
    
    sence_v(:,1) = +velocity(:,1)...
                   -velocity(:,3)...
                   +velocity(:,5)...
                   +velocity(:,6)...
                   -velocity(:,7)...
                   -velocity(:,8);
    sence_v(:,2) = -velocity(:,2)...
                   +velocity(:,4)...
                   +velocity(:,5)...
                   -velocity(:,6)...
                   -velocity(:,7)...
                   +velocity(:,8);
    
    new_position = sence_v .* if_is_too_crowd(people_position,sence_v,grid_people_map) .* if_is_out(people_position,sence_v,field_of_map) + people_position;
    %new_position = sence_v .* if_is_out(people_position,sence_v,field_of_map) + people_position;
    new_x = new_position(:,1);
    new_y = new_position(:,2);
    new_x(new_x>map_size(1)) = map_size(1);
    new_y(new_y>map_size(2)) = map_size(2);
    new_position = [new_x, new_y];
    new_position(new_position<1) = 1;
    
end